# python实现高斯消元法_LRC

In [1]:
class Gauss:
    def __init__(self):
        print("输入矩阵的行数：")
        self.n = int(input())
        print("输入矩阵的列数：")
        self.m = int(input())
        print("依次输入矩阵的每一行，一行以空格隔开每个数")
        self.matrix = [[0]*self.m]*self.n
        for i in range(self.n):
            self.matrix[i] = input().split(" ")
            for j in range(self.m):
                self.matrix[i][j] = int(self.matrix[i][j])
            
    def check(self):
        print(self.matrix)
        return
    
    #求最大公约数
    def gcd(self,a,b):
        if(b==0):
            return a
        return self.gcd(b,a%b)
    
    #第i行符号翻转
    def rvs(self,x):
        for j in range(self.m):
            self.matrix[x][j]*=(-1)
        return
    
    #找到第i行的第一个非0数所在列
    def findzero(self,i):
        for j in range(self.m):
            if(self.matrix[i][j]!=0):
                return j
        #没找到
        return -1
    
    #以第line行第col列为基准，消除s到t-1行的col列为0
    def clr(self,line,col,s,t):
        for i in range(s,t):
            #是0，不需要变
            if(self.matrix[i][col]==0):
                continue
            #小于0，整行符号翻转，便于后面最大公约数的计算
            if(self.matrix[i][col]<0):
                self.rvs(i)
            #算出最大公约数z，这一行所需要乘的因子x，k这一行所需要乘的因子y
            z=self.gcd(self.matrix[line][col],self.matrix[i][col])
            x=self.matrix[i][col]/z
            y=self.matrix[line][col]/z
            #将第i行所有列进行操作
            for l in range(self.m):
                self.matrix[line][l]*=x
                self.matrix[i][l]*=y
                self.matrix[i][l]-=self.matrix[line][l]
                #这里我觉得系数还原比较好，不然系数会越来越大
                self.matrix[line][l]/=x
        return
                
    #高斯消元法得到行阶梯型矩阵
    def ex_clr(self):
        #进行到第line行
        line=0
        #从左到右扫
        for j in range(self.m):
            #最后一行退出
            if(line==self.n-1):
                break
            #找这一列的第一个非0数所在行号
            pos=-1
            for i in range(line,self.n):
                if(self.matrix[i][j]!=0):
                    pos=i
                    break
                #这一列全是0，进行下一列
            if(pos==-1):
                continue
                #这一列第一行是0，把第一行变为非0
            if(pos!=0):
                for k in range(j,self.m):
                    self.matrix[line][k]+=self.matrix[pos][k]
            self.clr(line,j,line+1,self.n)
            #self.check()
            line+=1
        return
    
    #对行阶梯型矩阵继续进行高斯消元法得到最简行阶梯型矩阵
    def min_clr(self):
        #从上往下扫每一行
        for i in range(self.n):
            #找到这一行第一个非0数所在列
            pos=self.findzero(i)
            #进行该操作时已经时行阶梯型矩阵，遇到全0行可以直接退出
            if(pos==-1):
                break
            #将之前所有行的这一列消为0
            self.clr(i,pos,0,i)
        #self.check()
        
        #系数归1
        for i in range(self.n):
            pos=self.findzero(i)
            if(pos==-1):
                break
            x=self.matrix[i][pos]
            for j in range(pos,self.m):
                self.matrix[i][j]/=x
        return

Gauss类说明：

变量：
1. n,m：矩阵大小n行m列
2. matrix二维数组：存放矩阵
函数：
1. __init__：构造函数。
2. check函数；打印二维数组，用于debug。
3. gcd函数：求最大公约数。
4. rvs函数：翻转某一行的符号
5. findzero函数：寻找某一行第一个出现的非0数所在列并返回
6. clr函数：基于(line,col)将s到t-1行col列消为0的初等行变换
7. ex_clr函数：化为行阶梯型矩阵
8. min_clr函数：化为最简行阶梯型矩阵

其他：
1. 利用了最大公约数和最小公倍数，因此只能进行矩阵为整数的变换。
2. 在试图消为行阶梯型矩阵时，原本可以只对目标列之后的所有列进行系数变化，因为目标列之前的列一定是0，但为了代码能够在消为最简时复用，我将这个操作封装成了clr函数，如果需要可以在这里进行优化。
3. 问题：最终输出结果中有-0，有点影响美观。

In [2]:
import numpy as np

opr=Gauss()
opr.ex_clr()

print("行阶梯型矩阵：")
#这里让二维数组打出来更好看
print(np.array(opr.matrix))

opr.min_clr()
print("最简行阶梯型矩阵：")
print(np.array(opr.matrix))

输入矩阵的行数：
4
输入矩阵的列数：
5
依次输入矩阵的每一行，一行以空格隔开每个数
2 -1 4 -3 -4
1 0 1 -1 -3
3 1 1 0 1
7 0 7 -3 3
行阶梯型矩阵：
[[ 2. -1.  4. -3. -4.]
 [ 0.  2. -4.  2. -4.]
 [ 0.  0.  0. 16. 96.]
 [ 0.  0.  0.  0.  0.]]
最简行阶梯型矩阵：
[[ 1. -0.  1. -0.  3.]
 [ 0.  1. -2.  0. -8.]
 [ 0.  0.  0.  1.  6.]
 [ 0.  0.  0.  0.  0.]]


## 